### ISSUE TITLE
using decode node and encode node together doesn't return the original msg

### ISSUE THREAD

**Issue by jmikerq** [baumblatt/node-red-contrib-crypto-js#1]
Hello @baumblatt 

I was testing this node module and played around with the sample flow. Here is my flow:

```
[{"id":"99d70efc.dbd86","type":"inject","z":"543e65ad.2f3a4c","name":"Hello World","topic":"","payload":"Hello World","payloadType":"str","repeat":"","crontab":"","once":false,"x":141.11109924316406,"y":751.111083984375,"wires":[["15e204d8.79ab8b"]]},{"id":"31132bff.f80c64","type":"debug","z":"543e65ad.2f3a4c","name":"","active":true,"console":"false","complete":"false","x":696.3332977294922,"y":746.5555515289307,"wires":[]},{"id":"15e204d8.79ab8b","type":"decode","z":"543e65ad.2f3a4c","name":"Dec: base64","encode":"Base64","x":340.4444351196289,"y":748.777774810791,"wires":[["2a8f2dcc.4cab02"]]},{"id":"2a8f2dcc.4cab02","type":"encode","z":"543e65ad.2f3a4c","name":"Enc: Base64","encode":"Base64","x":524.4444732666016,"y":745.5555648803711,"wires":[["31132bff.f80c64"]]}]
```

So I have a decode node in base64 mode, followed by an encoded node in base64 mode, the return msg is "HelloAWorlc=" instead of "Hello World". 

I further checked with this flow in Hex mode, and it returns "00000000000d"

This flow seems working fine with other encode types.

My node-red is running @0.17.5, and node@6.10.3.

Thanks!
Michael Qiu

**Comment by baumblatt** [comment]
Hello Micheal,

As I can see in your flow, you are trying to decode the word `Hello World` that is not in base64 encoding. The base64 form of `Hello World` is `SGVsbG8gV29ybGQ=`.


Take a look at the base64 test flow from `samples/flows.json`.

    [{"id":"9d0a81b9.65eff","type":"inject","z":"6536b5ea.65654c","name":"Hello World","topic":"","payload":"Hello World","payloadType":"str","repeat":"","crontab":"","once":false,"x":130,"y":100,"wires":[["3f545b28.ab0c84"]]},{"id":"fe0bf0db.654d5","type":"debug","z":"6536b5ea.65654c","name":"","active":true,"console":"false","complete":"false","x":1033,"y":101,"wires":[]},{"id":"26c7be7d.9e5842","type":"encode","z":"6536b5ea.65654c","name":"Enc: Base64","encode":"Base64","x":489,"y":101,"wires":[["fc96e996.3a59c8","582dd64.d503728"]]},{"id":"fc96e996.3a59c8","type":"decode","z":"6536b5ea.65654c","name":"Dec: base64","encode":"Base64","x":676,"y":101,"wires":[["165f4d6b.b333b3"]]},{"id":"3f545b28.ab0c84","type":"decode","z":"6536b5ea.65654c","name":"Dec: utf8","encode":"Utf8","x":320,"y":101,"wires":[["26c7be7d.9e5842"]]},{"id":"165f4d6b.b333b3","type":"encode","z":"6536b5ea.65654c","name":"Enc: utf8","encode":"Utf8","x":853,"y":101,"wires":[["fe0bf0db.654d5"]]},{"id":"582dd64.d503728","type":"debug","z":"6536b5ea.65654c","name":"","active":true,"console":"false","complete":"false","x":699,"y":175,"wires":[]}]

Please, let me know if you need more help in this issue.

Best Regards,
Bernardo Baumblatt.

**Comment by jmikerq** [comment]
my apologies. I think I problem was that two nodes were put in the wrong order. Thanks!
